### PR TITLE
Updated rio.py for Python 3.10 compatability

### PR DESCRIPTION
**Pull request by neillt**
I removed all loop parameter language for compatibility with Python 3.10.5.  No other changes made.

### CODE REVIEW

**Comment by balloob** [comment]
For background on the issue that this PR fixes, see [this StackOverflow answer](https://stackoverflow.com/a/60315290)

**Review by bwest1711 — APPROVED** [review]

**Comment by neillt** [comment]
It works on my MCA-88X and my MBX-AMP.  Those are the only 2 Russound units I have to test against.

**Comment by bwest1711** [comment]
I have an MCA-88 and it works there as well.

**Comment by heidle78** [comment]
Any ideas how to integrate it to HA OS - I can´t access the file

**Comment by heidle78** [comment]
@bwest1711 
@wickerwaka 

Just a short question, do you use this as a standalone solution or within homeassistant? I actually have issues with HA and search for a solution. Any feedback is really apreciated!

**Comment by neillt** [comment]
@heidle78 I use it for HA.  What is your issue?  Probably best to move this somewhere other than a closed issue thread here.

**Comment by heidle78** [comment]
HA doesn’t ´t show any integration cards of the Russound. I was opening an issue on HA/core but I guess nobody is working on it - it´s a niche sub-project of HA and just limited users. So I tried to understand if I can do anything on my own to find a solution

**Comment by neillt** [comment]
DId you add the integration in your configuration.yaml?  It's a manually added integration.

Then once it's added, you need to manually add media player or entity cards for each zone and source where you want it on the dashboards.

**Comment by heidle78** [comment]
Integration I did exactly as mentioned in the documentation - but not the manually process with the cards and the media player. That´s new for me. I remember when I installed it a year ago all the entity cards where created automatically.

**Comment by heidle78** [comment]
I added the normal part to configuration.yaml
As soon as I start to define the zones and sources in the YAML then it complains

**Comment by heidle78** [comment]
And I can´t find any entities within HA - that´s also strange

**Pull request merged**
