### PR TITLE
fix ensure_future errors in python 3.7+

### PR DESCRIPTION
**Pull request by Hisma**
This plugin is broken on home assistant .88 and above.  The file has been modified to change all instances of "ensure_future" to "asyncio.ensure_future".  With these changes, the plugin works correctly again in home assistant .88+.

### CODE REVIEW

**Comment by wickerwaka** [comment]
Hi, thanks for this. Can you clean up all of the additional whitespace in the PR please?

**Comment by Hisma** [comment]
done! Huge pain in the ass sorry for all the commits.  I copy/pasted my code instead of modifying the existing code which created all those whitespace changes.  It's all cleaned up now.  Let me know if that works for you.

**Comment by Hisma** [comment]
Should I just do a new clean commit?  I see now it wants to merge all my commits instead of the latest.  Sorry.  Not something I do often obviously.  Or perhaps you can see my changes and just update yourself.  It's a very simple update.

**Comment by wickerwaka** [comment]
I have addressed this in a way that will still work for python 3.4+

**Pull request closed without merging**
